name: Build RustDesk
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc
      - name: Install dependencies
        run: |
          choco install -y pkgconfiglite
          vcpkg install libvpx libyuv opus
          vcpkg integrate
        shell: powershell
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc
        env:
          RENDEZVOUS_SERVER: rustdesk.getdevnet.com:21116
          RELAY_SERVER: rustdesk.getdevnet.com:21117
          RS_PUB_KEY: hMIWToeeSHrfJLZPWApfwLRm3P15T8hvwrxAskPwjPg=
          API_SERVER: http://rustdesk.getdevnet.com:21114
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: target/x86_64-pc-windows-msvc/release/rustdesk.exe
