name: Windows Lite RustDesk

on:
  workflow_dispatch:
    inputs:
      relay:
        description: 'Relay server host:port'
        required: true
        type: string
        default: 'rust.zont.uk:21117'
      idserver:
        description: 'ID server host:port'
        required: true
        type: string
        default: 'rust.zont.uk:21116'
      api:
        description: 'API server URL'
        required: true
        type: string
        default: 'http://rust.zont.uk:21114'
      key:
        description: 'Server key'
        required: true
        type: string

jobs:
  build-lite:
    runs-on: windows-2022
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Flutter
        uses: subosito/flutter-action@v2
